# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kaster.io
    url: https://kaster.io/
  - name: Tankengine (APP)
    url: https://the.tankengine.app/
  - name: Tankengine (Marketing)
    url: https://www.tankengine.app/
  - name: Realtors wordsmith (APP)
    url: https://app.realtorwordsmith.com/dashboard
  - name: Realtors wordsmith (Marketing)
    url: https://www.realtorwordsmith.com/
  - name: URLTrack (APP)
    url: https://app.urltrack.io/dashboard
  - name: URLTrack (Marketing)
    url: https://www.urltrack.io/
  - name: RubbertHunt
    url: https://www.rubberhunt.com/
  - name: Portal
    url: https://portal-kaster-io.vercel.app/
  - name: TankEngine
    url: https://the.tankengine.app/
    
assignees: # Users to assign downtime issues (optional)
  - EHDMC
  - raudindev
  - brandon-kaster

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitoring the reliability of **Kaster.io**'s web services"
  introMessage: Welcome to the status page for Kaster.io's online services. Here, you can find real-time updates on the operational status of all our platforms. We strive to maintain high availability and quickly address any issues that arise. Thank you for trusting us with your digital needs.
